### ISSUE TITLE
`-` in project name breaks the template janitor

### ISSUE THREAD

**Issue by lefticus** [cpp-best-practices/cmake_conan_boilerplate_template#21]
Because the project name is used in C++ code, this becomes converted to an invalid identifier in the namespace `project-name::value` is not valid C++.

We should try to see if we can fix-up `-` to `_` at template janitor time.

Re: @LtdSauce

**Comment by LtdSauce** [comment]
I'll try to work on this this evening when the Kids are in bed :)

**Comment by lefticus** [comment]
> I'll try to work on this this evening when the kids are in bed :)

Thanks, if you can! 

Right now I'm collecting and triaging a bunch of issues found by my game-jam participants.

**Comment by LtdSauce** [comment]
Maybe we should try and catch more naming issues with this one. So far i found out, that it is possible to include the following symbols in github repository names:
- `.`: Obviousyl this will break a lot when used in C++ code
- `-`: Already mentioned, not allowed in C++ identifier
- preceding the name with numbers: Not allowed in C++ identifier
- tbc..?

Many of the special symbols like `!"§$%&/?,` will be converted by github into `-` either way. So we don't have to care about them.
