### ISSUE TITLE
clang-tidy version should be fixed

### ISSUE THREAD

**Issue by dholmes215** [cpp-best-practices/cmake_conan_boilerplate_template#37]
The version of clang-tidy should be specified in ci.yml to prevent it from changing. For example, `clangtidy: 13.0.0` instead of `clangtidy: true`

To prevent it from being clobbered by the compiler setup, it should be the same as the clang/LLVM version.

**Comment by lefticus** [comment]
Fixed in 235115d92a4909c4a1571dae202d11e6337868c4
